#PLAYBOOK to install DOCKER:
- name: install docker and run docker
  hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker
    package: name=docker state=present
  - name: start service
    service: name=docker state=started
